---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: bluebox
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 43

modules:
  - type: files
    files:
      - source: system/common
        destination: /

  - type: dnf
    install:
      packages:
        - git
        - git-subtree

  - from-file: partials/common.yml
  - from-file: partials/brew.yml
  - from-file: partials/zed.yml
  - from-file: partials/firefox.yml
  - from-file: partials/1password.yml
  - from-file: partials/flatpaks.yml
  - from-file: partials/gnome.yml
  - from-file: partials/refind.yml
  - from-file: partials/grub.yml
  - from-file: partials/nvidia.yml
  - from-file: partials/chezmoi.yml

  - type: signing
